### PR TITLE
Now you can specify the AZ !! :)

### PR DESCRIPTION
**Pull request by delichty**
Found that I needed to specify the AZ to deploy into. Another feature I thought others might find useful.

### CODE REVIEW

**Comment by peterb154** [comment]
@delichty I think we should use the aws_availibility_zones data source https://www.terraform.io/docs/providers/aws/d/availability_zones.html and pick the first az in the list, rather that defining a second variable that would need to be configured whenever the region variable changes.

**Comment by delichty** [comment]
@peterb154 I actually had that exact code in there to start, but had a problem selecting the specific AZ I wanted. So I just went with a static variable for ease and speed.

I will put the code I had back in and update this PR, then we can take it from there.

Thanks!

**Comment by delichty** [comment]
@peterb154 I'm not a huge fan of the way this is implemented, but it is the easiest way I could make it work. I fought a little trying to get so I could specify an AZ like `us-west-1b`, but I couldn't get it to work. Instead, I just used a simple index. Not the most robust either, but it will work.

I set the defaults to keep the same behavior, region `us-east-1` and availability zone `us-east-1a`.

**Comment by delichty** [comment]
Found another little bug, this time in `tf_instance.sh`. The bash script was setting the variable as `allowed_cidrs`, but the `terraform.tf` had that variable named `allowed_cidr`. Therefore, it was setting the SG to be open to `0.0.0.0/0`.

**Pull request merged**
